[muzimakzi] 데이터 모델
wecode-bootcamp-korea/31-1st-MUZIMAKZI-backend pull request #2
Opened 2022-03-29 10:01 UTC by gleehave

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- Django app을 생성하고, 각 앱의 models.py에 데이터 모델 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. users 앱, carts 앱, products 앱 생성
2. 각 앱에 필요한 모델 정의
    - users앱 : users 테이블
    - carts 앱: carts 테이블
    - products앱: products, products_options, images, sizes, colors, types, categories 테이블
![스크린샷 2022-03-29 오후 7 00 28](https://user-images.githubusercontent.com/91510831/160586686-f3165bf0-b4bf-47da-ab07-93938b15e864.png)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- git branch간의 merge를 수행함. 이를 통해, 독립적으로 기능 구현 후 기능을 병합하는 작업을 수월히 진행할 수 있었음.
- 코드적인 모델 작업 보다, 이해와 상호간의 의견조율을 통해 얻은 개념적 데이터 모델링이 매우 중요함을 깨달음.

<br />

## :: 기타 질문 및 특이 사항
- DB I/O가 많은 테이블에 대해서 효율을 높일 수 있는 모델링이 따로 있는지 궁금합니다.

2022-03-29 17:27 UTC, jamessoun93 requested changes

2022-03-29 17:27 UTC, jamessoun93 commented on users/models.py
> +        abstract = True
해당 abstract 모델은 다른곳에서도 상속받고 있으니 users app 밖에서 선언해주세요.

2022-03-29 17:27 UTC, jamessoun93 commented on products/models.py
> +        return self.product
커머스인데 재고관리가 되어야하지 않을까요?

2022-03-29 17:27 UTC, jamessoun93 commented on products/models.py
> +    price       = models.DecimalField(max_digits=9, decimal_places=3)
currency 관련 DecimalField는 글로벌하게 소수점 두자리로 통일되고 있으니 그에 맞춰주세요.

2022-03-29 17:27 UTC, jamessoun93 commented on products/models.py
> +    tag         = models.CharField(max_length=100)
이건 그냥 몰라서 여쭤보는건데 제품 tag가 하나만 등록 가능하고 다른 제품에는 같은 tag가 쓰이지 않나요?

2022-03-29 17:27 UTC, jamessoun93 commented on products/models.py
> +    thumbnail   = models.URLField(max_length=2000)
`thumbnail_image_url` 처럼 명확한 컬럼명을 지정해주세요.

2022-03-29 17:27 UTC, jamessoun93 commented on products/models.py
> +    thumbnail = models.URLField(max_length=2000)
`thumbnail_image_url` 처럼 명확한 컬럼명을 지정해주세요.

2022-03-30 02:10 UTC, gleehave commented on users/models.py
> +        abstract = True
늦은시간에도 리뷰 남겨주셔서 감사드립니다!

기존: users app에 있던 abstract 모델 -> 변경: core 디렉토리/ models.py 로 옮겨 수정하였습니다.

2022-03-30 02:11 UTC, gleehave commented on products/models.py
> +        return self.product
Product_option 클래스에 stock 필드를 생성해서 수량관리를 할 수 있도록 수정하였습니다!

수정: stock = models.IntegerField()

2022-03-30 02:15 UTC, gleehave commented on products/models.py
> +    price       = models.DecimalField(max_digits=9, decimal_places=3)
Price 소수점 2자리로 통일 될 수 있도록 deciaml_places을 수정하였습니다.

수정: price = models.DecimalField(max_digits=9, decimal_places=2)

2022-03-30 02:17 UTC, gleehave commented on products/models.py
> +    tag         = models.CharField(max_length=100)
다른 제품에 같은 Tag가 사용될 수 있습니다.
Tag 테이블을 하나 더 생성해서 데이터 모델을 수정하였습니다.
![스크린샷 2022-03-30 오전 11 16 53](https://user-images.githubusercontent.com/91510831/160737394-c0b895ef-e736-49f2-92ad-051111911dc0.png)

2022-03-30 02:17 UTC, gleehave commented on products/models.py
> +    thumbnail   = models.URLField(max_length=2000)
명확한 필드명인 thumbnail_image_url 으로 수정하였습니다!

2022-03-30 02:17 UTC, gleehave commented on products/models.py
> +    thumbnail = models.URLField(max_length=2000)
명확한 필드명인 thumbnail_image_url 으로 수정하였습니다!

2022-03-30 04:50 UTC, jamessoun93 commented on products/models.py
> +    tag         = models.CharField(max_length=100)
다른 제품에 같은 tag가 사용될 수 있다면 M2M으로 관계 설정을 해주셔야겠네요.

2022-03-30 06:58 UTC, jamessoun93 requested changes

2022-03-30 06:58 UTC, jamessoun93 commented on products/models.py
> +class Product_option(models.Model):
```suggestion
class ProductOption(models.Model):
```

2022-03-30 07:06 UTC, gleehave commented on products/models.py
> +class Product_option(models.Model):
수정 완료하였습니다!

2022-03-30 07:08 UTC, jamessoun93 approved these changes
LGTM 👍

2022-03-30 07:08 UTC, merged