[ADD]: 로그인, 회원가입 뷰 작성
wecode-bootcamp-korea/31-1st-MUZIMAKZI-backend pull request #3
Opened 2022-03-30 09:05 UTC by youbeemuhwan

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- users 모델의 회원정보를 받아 회원가입 및 로그인

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입 데이터 처리
- 입력 받은 이메일의 중복 되지 않게 체크해주는 코드 작성
- 정규식과 조건문을 이용하여 email, password 유효성 검사 진행
- 암호화를 위해 회원가입 시 입력받은 password를 해싱한뒤 DB에 보관하기 위해 디코딩 진행 

2. 로그인 데이터 처리
- 입력 받은 email 이 현재 가입된 email 인지 체크 하는 코드 작성
- 입력 받은 password 가 입력 받은 email의 password가 맞는지 체크하는 코드 작성
- 로그인 성공 시 토큰을 반환해주는 코드 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 로그인 기능을 작성하며 각 쿼리셋 메서드의 반환값의 중요성에 대해 알게되었다.
- 기본적인 예외 처리, 입력받은 데이터를 어떻게 처리해야 되는지에 대한 기본적인 로직들을 알수있는 시간 이었습니다.

<br />

## :: 기타 질문 및 특이 사항
- 예외 처리를 할떼 각 에러 마다 일일히 import로 선언 해주는것이 맞는건가요?

2022-03-31 05:55 UTC, jamessoun93 requested changes

2022-03-31 05:55 UTC, jamessoun93 commented on users/validation.py
> +from django.forms import ValidationError
저희는 form을 사용하지 않기때문에 django.core.exceptions 로부터 import 하는 방법으로 변경해주세요!
```suggestion
from django.core.exceptions import ValidationError
```

2022-03-31 05:55 UTC, jamessoun93 commented on users/validation.py
> +    return True
함수명은 이렇게 만드시면 안됩니다. 앞에 대문자가 붙으면 클래스인줄 알고 헷갈릴수가 있어서요.
```suggestion
def validate_email(email) :
    
    validator = re.compile('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$')
    
    if not validator.match(email) :
        raise ValidationError
    
    return True

def validate_password(password) :
    
    validator = re.compile("^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$")
    
    if not validator.match(password) :
        raise ValidationError
    
    return True
```

2022-03-31 05:55 UTC, jamessoun93 commented on users/views.py
> +from django.forms import ValidationError
저희는 form을 사용하지 않기때문에 django.core.exceptions 로부터 import 하는 방법으로 변경해주세요!

2022-03-31 05:55 UTC, jamessoun93 commented on users/views.py
> +            if User.objects.filter(email = data["email"]) :
이럴때는 존재여부를 판단하여 boolean 으로 return해주는 exists() 메소드를 사용해주시는게 좋습니다.

2022-03-31 05:55 UTC, jamessoun93 commented on users/views.py
> +                    return JsonResponse({"MESSAGE" : "ALREADY EXITSTS EMAIL"}, status = 400)
이미 존재하는 리소스일때 반환해주면 좋은 HTTP Status Code가 뭘까요?

2022-03-31 05:55 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({"MESSAGE" : "SUCCESS"}, status = 200)
200도 맞긴하지만 POST /signup 같은경우 더 명확한 status code를 지정해줄 수 있습니다.

2022-03-31 05:55 UTC, jamessoun93 commented on users/views.py
> +            if not User.objects.filter(email=email) :
여기서도 exists() 활용해주시면 되겠네요.

2022-03-31 05:55 UTC, jamessoun93 commented on users/views.py
> +                return JsonResponse({'MESSAGE' : 'INVALID EMAIL OR PASSWORD'}, status = 400)
이런 상황에 반환해줄 수 있는 더 명확한 status code는 뭐가 있을까요? (400대는 맞습니다)

2022-03-31 05:55 UTC, jamessoun93 commented on users/views.py
> +        JsonResponse({"MESSAGE" : "KEY_ERROR"}, status = 400)
`try ... except ...`는 해당 메소드안의 로직을 실행하는동안 (런타임) 발생할 수 있는 exception을 처리하기 위함이라 메소드 전체를 감싸는게 아니고 메소드 안으로 넣어주세요.

2022-03-31 05:56 UTC, jamessoun93 commented
다음부터는 실제 호출결과를 첨부해주세요.
작성해주신 코드를 보니 충분한 테스트를 거치지 않은채로 올라온 것 같아서요.
수정해서 다시 올려주세요~

2022-03-31 06:28 UTC, youbeemuhwan commented
<img width="770" alt="MUZIMAKZI_회원가입뷰_결과" src="https://user-images.githubusercontent.com/93572207/160990304-93979bf2-94a6-4a9f-b541-b2c2190608bd.png">
<img width="770" alt="MUZIMAKZI_로그인뷰_결과" src="https://user-images.githubusercontent.com/93572207/160990307-5679b1b2-24e3-412f-b04b-73f2a3ef977b.png">

제가 깜빡하고 결과 사진을 업로드를 안했습니다. 
수정 전 결과 사진 입니다! 수정하고 다시 결과 사진과 같이 PR 올리겠습니다!

2022-03-31 06:31 UTC, youbeemuhwan commented on users/validation.py
> +from django.forms import ValidationError
네! 수정하겠습니다!

2022-03-31 06:32 UTC, youbeemuhwan commented on users/validation.py
> +    return True
아하.. 염두하고 수정하겠습니다!

2022-03-31 06:32 UTC, youbeemuhwan commented on users/views.py
> +from django.forms import ValidationError
넵 수정하겠습니다!

2022-03-31 06:36 UTC, youbeemuhwan commented on users/views.py
> +            if User.objects.filter(email = data["email"]) :
넵! 저는 filter 메서드 결과가 없으면 빈 쿼리셋을 가져오는데 빈쿼리셋은 파이썬에서 False 값으로 인식되어지니 굳이 exists() 메서드 까지 쓰면 투머치가 아닌가 라고 생각에서 작성한 코드였습니다 ㅠㅠ 혹시 제가 생각한 부분에서 부족한 점이 있는지 여쭤봐도 될까요?

2022-03-31 06:42 UTC, youbeemuhwan commented on users/views.py
> +            return JsonResponse({"MESSAGE" : "SUCCESS"}, status = 200)
201  : 요청이 성공적으로 받아들여졌으며 서버가 새 리소스를 작성하였다.   - 200 보다 더 명확한 status code 라고 생각 했습니다.

2022-03-31 06:42 UTC, youbeemuhwan commented on users/views.py
> +            if not User.objects.filter(email=email) :
네 수정하겠습니다!

2022-03-31 06:55 UTC, youbeemuhwan commented on users/views.py
> +                return JsonResponse({'MESSAGE' : 'INVALID EMAIL OR PASSWORD'}, status = 400)
409 (Conflict) - 리소스의 현재 상태와 충돌하여 요청을 처리 할수가 없으므로 클라이언트가 요청을 수정해서 다시 요청해야되는 경우에 사용한다. 라고 이해 해서 409 코드라고 생각합니다!

2022-03-31 06:56 UTC, youbeemuhwan commented on users/views.py
> +                    return JsonResponse({"MESSAGE" : "ALREADY EXITSTS EMAIL"}, status = 400)
아래의 답변과 같이  409 (conflict) 라고 생각합니다!

2022-03-31 07:02 UTC, youbeemuhwan commented on users/views.py
> +                return JsonResponse({'MESSAGE' : 'INVALID EMAIL OR PASSWORD'}, status = 400)
401 (Unauthorized) 라고 생각합니다. 인증되지 않는 정보로 로그인을 할려고 했기에 미승인, 비인증 의 의미를 가진 401 code가 적합하다고 생각합니다.

2022-03-31 07:03 UTC, youbeemuhwan commented on users/views.py
> +        JsonResponse({"MESSAGE" : "KEY_ERROR"}, status = 400)
큰 실수를 햇네요 ㅠㅠ 염두하고 수정하겠습니다.

2022-03-31 07:24 UTC, youbeemuhwan commented
<img width="770" alt="MUZIMAKZI_회원가입뷰_수정 후 결과" src="https://user-images.githubusercontent.com/93572207/161000605-5bcb31a7-8e2a-4231-96e5-3703f7cc9131.png">
<img width="770" alt="MUZIMAKZI_로그인뷰_수정 후 결과" src="https://user-images.githubusercontent.com/93572207/161000612-bbcd01aa-f846-400a-951a-a1d7322c5752.png">

수정 후 결과 올립니다!

2022-03-31 08:23 UTC, jamessoun93 commented on users/views.py
> +            if User.objects.filter(email = data["email"]) :
사실 exists()는 존재여부만 확인할때 쓰는거라 지금과 같이 동일한 이메일주소로 유저 객체를 어짜피 가져와야하는 경우 exists를 사용하는것보다는 기존에 작성해주신 형태로 bool(queryset)의 형태로 작성해주시는게 더 효율적입니다. 하지만 여기서는 아래에서 get()을 통해 단일객체를 가져오는 쿼리를 어짜피 날리기때문에 if문에서는 exists()를 붙여서 사용하는게 내부적으로는 더 효율적입니다.

2022-03-31 08:24 UTC, jamessoun93 commented on users/views.py
> +                    return JsonResponse({"MESSAGE" : "ALREADY EXITSTS EMAIL"}, status = 400)
409 사용해주시면 됩니다~

2022-03-31 08:24 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({"MESSAGE" : "SUCCESS"}, status = 200)
넵!

2022-03-31 08:24 UTC, jamessoun93 commented on users/views.py
> +                return JsonResponse({'MESSAGE' : 'INVALID EMAIL OR PASSWORD'}, status = 400)
넵!

2022-03-31 08:24 UTC, jamessoun93 commented on users/views.py
> +        JsonResponse({"MESSAGE" : "KEY_ERROR"}, status = 400)
👍

2022-03-31 08:30 UTC, youbeemuhwan commented on users/views.py
> +                    return JsonResponse({"MESSAGE" : "ALREADY EXITSTS EMAIL"}, status = 400)
409 라 해놓고 왜 401 이라 썻을까요... 제가 이렇게 정신이 없습니다...

2022-03-31 08:31 UTC, youbeemuhwan commented on users/views.py
> +            if User.objects.filter(email = data["email"]) :
제가 아직 쿼리에  대한 이해가 부족한거같네요. mysql 도 공부해보고 싶네요.

2022-03-31 08:47 UTC, jamessoun93 requested changes

2022-03-31 08:47 UTC, jamessoun93 commented on users/views.py
> +                                    "access_token" : access_token}, status = 200)
```suggestion
            return JsonResponse({
                "message"      : "SUCCESS",
                "access_token" : access_token
            }, status = 200)
```

2022-03-31 08:47 UTC, jamessoun93 commented on users/views.py
> +                                    "access_token" : access_token}, status = 200)
하나만 더 수정해주세요~

2022-04-01 05:06 UTC, bigfanoftim approved these changes
LGTM 👍

2022-04-01 05:06 UTC, merged