[muzimakzi] 데이터모델 수정 및 ProductListView 다중필터 적용
wecode-bootcamp-korea/31-1st-MUZIMAKZI-backend pull request #5
Opened 2022-04-04 06:32 UTC by gleehave

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [x] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 추기 기능 구현을 위한 데이터 테이블 생성
- 테이블간 related_name 삭제, (product_set 으로 통일되게끔)
- ProductListView 에서 다중 필터 적용

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 데이터 모델 생성
    - WishList 클래스 작성
2. 데이터 모델 외래키 관계 이름 설정
    - related_name을 전부 제거 ( _set 으로 통일되게 사용할 수 있도록 함.)
3. ProductListView 에서 다중 필터 적용
    - Query parameter 를 통해서 데이터 받음.    
    - Q객체 사용
    - 다중필터 적용 (2개의 태그필터를 적용한다면, 2개의 필터를 모두 갖는 product를 반환)
<img width="967" alt="스크린샷 2022-04-04 오후 3 31 31" src="https://user-images.githubusercontent.com/91510831/161486150-459544bf-2e7c-4d5e-a3a4-9ebc3717cfcf.png">
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- SQL 언어를 ORM으로 변환하여 작성함. 
- select GROUP_CONCAT(id) FROM tags_products GROUP BY product_id HAVING COUNT(DISTINCT CASE WHEN tag_id IN(1, 2) THEN tag_id END)=2;
- 위의 Query문으로 DB에 먼저 작업해서 결과를 받아본 후, Django ORM으로 맞춰서 작성.
- Django ORM으로 트랜잭션을 구성할 수 있다면, ORM으로 rollback으로 적용하는게 필요할 듯.

<br />

## :: 기타 질문 및 특이 사항
- 특이사항 없습니다.

2022-04-05 01:34 UTC, bigfanoftim requested changes

2022-04-05 01:34 UTC, bigfanoftim commented on products/urls.py
> +    path('/categories/<int:category_id>', ProductCategoryView.as_view()),
굳이 적어주지 않아도 되는 주석인것 같아요!
```suggestion
    path('/categories/<int:category_id>', ProductCategoryView.as_view()),
```

2022-04-05 01:34 UTC, bigfanoftim commented on products/urls.py
> +    path('/categories/list', ProductListView.as_view())
`list`를 굳이 적어주지 않아도 되겠습니다.
```suggestion
    path('/categories', ProductListView.as_view())
```

2022-04-05 01:34 UTC, bigfanoftim commented on products/views.py
> +from django.views import View
```suggestion
from django.db.models  import Q, Count
from django.http       import JsonResponse
from django.views      import View

from products.models import Type, Product, Tag, TagProduct
```

2022-04-05 01:34 UTC, bigfanoftim commented on products/views.py
> +            return JsonResponse({'message': 'invalid key'}, status=400)
API를 살펴보니 `TypeView`가 더 어울리는 이름인 것 같은데 한번만 다시 확인해주세요!
```suggestion
class TypeView(View):
    def get(self, request, category_id):
        try:
            types = Type.objects.filter(category=category_id)

            result = [{
                'name'          : type.name,
                'thumbnail_url' : type.thumbnail_image_url
            } for type in types]

            return JsonResponse({'message': result}, status=200)

        except KeyError:
            return JsonResponse({'message': 'invalid key'}, status=400)
```

2022-04-05 01:34 UTC, bigfanoftim commented on wishlist/models.py
> +    product_option = models.ForeignKey('products.ProductOption', on_delete=models.CASCADE)
```suggestion
    user           = models.ForeignKey('users.User', on_delete=models.CASCADE)
    product_option = models.ForeignKey('products.ProductOption', on_delete=models.CASCADE)
```

2022-04-05 01:34 UTC, bigfanoftim commented on products/views.py
> +class ProductListView(View):
`ProductListView`같은 경우는 오늘 오후에 진행하는 `live code review`시간에 자세히 리뷰 드리도록 하겠습니다!

2022-04-05 01:40 UTC, gleehave commented on products/urls.py
> +    path('/categories/<int:category_id>', ProductCategoryView.as_view()),
늘 꼼꼼히 리뷰해주셔서 정말 감사드립니다!
해당 주석은 삭제 처리 하겠습니다.

2022-04-05 01:43 UTC, gleehave commented on products/urls.py
> +    path('/categories/list', ProductListView.as_view())
넵! 해당 부분 수정하겠습니다.
수정 : path('/categories', ProductListView.as_view())

2022-04-05 01:45 UTC, gleehave commented on products/views.py
> +from django.views import View
import 부분의 들여쓰기 부분 통일하여 작성하겠습니다!

2022-04-05 01:47 UTC, gleehave commented on products/views.py
> +            return JsonResponse({'message': 'invalid key'}, status=400)
TypeView로 네이밍 수정하도록 하겠습니다!

2022-04-05 01:50 UTC, gleehave commented on wishlist/models.py
> +    product_option = models.ForeignKey('products.ProductOption', on_delete=models.CASCADE)
코드 컨벤션 맞춰서 수정하겠습니다!! ㅠㅠ

2022-04-05 01:51 UTC, gleehave commented on products/views.py
> +class ProductListView(View):
넵.. 감사합니다.. 질문 많이 하겠습니다!

2022-04-05 09:12 UTC, gleehave commented on products/views.py
> +class ProductListView(View):
live code review 이후에 코드 다중필터 코드 수정하였습니다!

2022-04-06 01:21 UTC, bigfanoftim commented on products/views.py
> +            } for product in products if len(product.tagproduct_set.all()) >= len(tags)]
혹시 여기서 태그수를 확인하는 이유가 뭔지 설명해주실 수 있나요?

2022-04-06 02:34 UTC, gleehave commented on products/views.py
> +            } for product in products if len(product.tagproduct_set.all()) >= len(tags)]
<img width="322" alt="스크린샷 2022-04-06 오전 11 30 44" src="https://user-images.githubusercontent.com/91510831/161883990-5b19a26c-ca82-482e-8b5e-1ed13fc974b5.png">

위의 데이터 베이스 구조에서
1개의 상품이 여러 tag를 갖고 있을 때 (예를 들어, 1번 상품이 tag 2개를 갖는다.),
사용자가 필터를 tag 2개를 요청할 경우, tag 2개를 모두 만족하는 상품 1개를 출력하려고 하였습니다.

만약 아래의 tag 개수를 점검하지 않는다면,
tag 필터 1, 2를 요청받았을 경우, 위의 데이터베이스 사진의 모든 product를 반환하게 되어서, 마지막에 tag 개수를 점검하는 조건을 추가하였습니다.

2022-04-06 07:59 UTC, bigfanoftim commented
조금만 힘내서 적용해봅시다 강호님!! 👍

2022-04-07 01:59 UTC, bigfanoftim approved these changes
LGTM 👍

2022-04-07 02:00 UTC, merged